namespace Solana.Unity.Metaplex.CandyGuard.Errors
{
    public enum CandyGuardErrorKind : uint
    {
        InvalidAccountSize = 6000U,
        DeserializationError = 6001U,
        PublicKeyMismatch = 6002U,
        DataIncrementLimitExceeded = 6003U,
        IncorrectOwner = 6004U,
        Uninitialized = 6005U,
        MissingRemainingAccount = 6006U,
        NumericalOverflowError = 6007U,
        RequiredGroupLabelNotFound = 6008U,
        GroupNotFound = 6009U,
        ExceededLength = 6010U,
        CandyMachineEmpty = 6011U,
        InstructionNotFound = 6012U,
        CollectionKeyMismatch = 6013U,
        MissingCollectionAccounts = 6014U,
        CollectionUpdateAuthorityKeyMismatch = 6015U,
        MintNotLastTransaction = 6016U,
        MintNotLive = 6017U,
        NotEnoughSOL = 6018U,
        TokenBurnFailed = 6019U,
        NotEnoughTokens = 6020U,
        TokenTransferFailed = 6021U,
        MissingRequiredSignature = 6022U,
        GatewayTokenInvalid = 6023U,
        AfterEndDate = 6024U,
        InvalidMintTime = 6025U,
        AddressNotFoundInAllowedList = 6026U,
        MissingAllowedListProof = 6027U,
        AllowedListNotEnabled = 6028U,
        AllowedMintLimitReached = 6029U,
        InvalidNftCollection = 6030U,
        MissingNft = 6031U,
        MaximumRedeemedAmount = 6032U,
        AddressNotAuthorized = 6033U,
        MissingFreezeInstruction = 6034U,
        FreezeGuardNotEnabled = 6035U,
        FreezeNotInitialized = 6036U,
        MissingFreezePeriod = 6037U,
        FreezeEscrowAlreadyExists = 6038U,
        ExceededMaximumFreezePeriod = 6039U,
        ThawNotEnabled = 6040U,
        UnlockNotEnabled = 6041U,
        DuplicatedGroupLabel = 6042U,
        DuplicatedMintLimitId = 6043U,
        UnauthorizedProgramFound = 6044U,
        ExceededProgramListSize = 6045U,
        AllocationNotInitialized = 6046U,
        AllocationLimitReached = 6047U,
        AllocationGuardNotEnabled = 6048U,
        InvalidMintAuthority = 6049U,
        InstructionBuilderFailed = 6050U,
        InvalidAccountVersion = 6051U
    }
}
